import { cn } from "@/shared/utils";
import type { Metadata } from "next";
import { Inter, Lato, Roboto } from "next/font/google";

import { Provider } from "@/app/providers/Provider";

import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["400", "500", "700", "600"],
});
const lato = Lato({
  subsets: ["latin"],
  variable: "--font-lato",
  weight: ["900", "700", "400", "300"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "700", "300"],
});

export const metadata: Metadata = {
  title: {
    absolute: "Flavor Fit",
    template: "%s | Flavor Fit",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          roboto.variable,
          lato.variable,
          inter.variable,
          "antialiased",
        )}
      >
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
