export const PAGES = {
  HOME: "/",
  DASHBOARD: "/dashboard",
  MEAL_PLANS: "/dashboard/meal-plans",
  NUTRITION: "/dashboard/nutrition",
  ANALYTICS: "/dashboard/analytics",
  ORDER_GROCERIES: "/dashboard/order-groceries",
  RECIPES: "/dashboard/recipes",
  FORUM: "/dashboard/forum",
  AUTH: "/auth",
  REGISTER: "/auth/register",
  LOGIN: "/auth/login",
  REQUEST_RESET_PASSWORD: "/auth/request-reset-password",
  RESET_PASSWORD: "/auth/reset-password",
  VERIFY_EMAIL: "/auth/verify-email",
} as const;
